Repository LikeLionSCH/9th_Pet_Promotion_Backend, pull requests merged in 2021-03, with the labels that each got.

#2 create_license
  LICENSE
Labels: documentation

#4 DRF Settings
  .gitignore
  pet_promotion/manage.py
  pet_promotion/projects/__init__.py
  pet_promotion/projects/asgi.py
  pet_promotion/projects/settings.py
  pet_promotion/projects/urls.py
  pet_promotion/projects/wsgi.py
  requirements.txt
Labels: TODO

#8 user model added
  pet_promotion/projects/settings.py
  pet_promotion/user/__init__.py
  pet_promotion/user/admin.py
  pet_promotion/user/apps.py
  pet_promotion/user/migrations/__init__.py
  pet_promotion/user/models.py
  pet_promotion/user/tests.py
  pet_promotion/user/views.py
Labels: TODO

#9 pet model added
  pet_promotion/user/models.py
Labels: TODO

#10 개발:: Post, Image, Comment 모델 설계 (율희)
  pet_promotion/board/admin.py
  pet_promotion/board/apps.py
  pet_promotion/board/models.py
  pet_promotion/board/tests.py
  pet_promotion/board/views.py
Labels: TODO

#23 오류수정::Custom User Admin Register Error (세환)
  pet_promotion/projects/settings.py
  pet_promotion/user/admin.py
  pet_promotion/user/migrations/0001_initial.py
  pet_promotion/user/models.py
Labels: bug

#27 Custom Admin Added
  pet_promotion/board/admin.py
  pet_promotion/board/migrations/0001_initial.py
  pet_promotion/board/migrations/0002_auto_20210301_2119.py
  pet_promotion/board/migrations/__init__.py
  pet_promotion/board/models.py
  pet_promotion/projects/settings.py
  pet_promotion/projects/urls.py
  pet_promotion/user/admin.py
  pet_promotion/user/migrations/0002_auto_20210301_2119.py
  pet_promotion/user/models.py
  pet_promotion/user/serializers.py
  pet_promotion/user/urls.py
  pet_promotion/user/views.py
Labels: TODO

#29 Login Token Added
  pet_promotion/projects/settings.py
  pet_promotion/user/serializers.py
  pet_promotion/user/urls.py
  pet_promotion/user/views.py
Labels: TODO

#31 Token 방식 교체 및 토큰으로 유저 조회 구현
  pet_promotion/projects/settings.py
  pet_promotion/requirements.txt
  pet_promotion/user/serializers.py
  pet_promotion/user/urls.py
  pet_promotion/user/views.py
Labels: TODO

#32 readme updates
  README.md
  pet_promotion/user/serializers.py
  pet_promotion/user/views.py
Labels: TODO

#34 개발:: HOST Setting
  pet_promotion/projects/settings.py
Labels: documentation

#42 수정 :: url 수정, user 조회 삭제
  pet_promotion/board/views.py
  pet_promotion/user/serializers.py
  pet_promotion/user/urls.py
  pet_promotion/user/views.py
Labels: TODO

#43 개발 :: 댓글 CRUD 구현
  pet_promotion/board/serializers.py
  pet_promotion/board/views.py
  pet_promotion/comment/__init__.py
  pet_promotion/comment/admin.py
  pet_promotion/comment/apps.py
  pet_promotion/comment/migrations/__init__.py
  pet_promotion/comment/models.py
  pet_promotion/comment/serializers.py
  pet_promotion/comment/tests.py
  pet_promotion/comment/urls.py
  pet_promotion/comment/views.py
  pet_promotion/projects/urls.py
  pet_promotion/user/serializers.py
  pet_promotion/user/views.py
Labels: TODO
